### PR TITLE
Fix slow queries

### PR DESCRIPTION
**Pull request by awbauer**
Adding JOIN to SQL requests improves performance for large tables.

Before (77,000ms): https://www.dropbox.com/s/a71uvxwvs98vlu5/Screenshot%202016-01-06%2014.30.17.png?dl=0

After (218ms): https://www.dropbox.com/s/sbb52i2k68vm9qi/Screenshot%202016-01-06%2014.30.46.png?dl=0

### CODE REVIEW

**Comment by BUWebTeam** [comment]
Mentioned on Slack by **Andrew Bauer** in **#wp-dev**. [View the logs :arrow_right:](https://buweb.slack.com/archives/wp-dev/p1452109993000645)

**Comment by awbauer** [comment]
Also see https://github.com/bu-ist/bu-section-editing/compare/hotfix/select-distinct...hotfix/no-temp-tables for an alternative that doesn't generate temp tables

**Comment by awbauer** [comment]
@inderpreet99 Sending this your way for review. 

Failed Travis checks are due to WP's 4.4.1 update yet being tagged. https://wordpress.slack.com/archives/core/p1452112621008643

**Comment by BUWebTeam** [comment]
Mentioned on Slack by **Andrew Bauer** in **#cms**. [View the logs :arrow_right:](https://buweb.slack.com/archives/cms/p1452184396001783)

**Comment by inderpreet99** [comment]
@awbauer, both of the queries look good. Due to the speed improvements of the subquery, I would vote for it to be used as it also avoids temp tables.

I will say that the temp tables problem that we're seeing is most likely due to having a very large WP site (`tech`). The joins are supposed to be as efficient as the subqueries. And in latest versions of MySQL (which we are not using), the subqueries are typically converted into joins by the optimizer.

Also, you could probably remove this comment from that function:
```
@todo re-examine and optimize this query
```

Great investigative work here!

**Pull request merged**
